create table users(id integer primary key, name text, passwd text, online text, fd integer);
insert into users(name, passwd, online, fd) values('root', 'root', 'off', -1);
insert into users(name, passwd, online, fd) values('troy', 'troy', 'off', -1);
create table troy(id integer primary key, name text, log_type integer);
insert into troy(name, log_type) values('ivy', -1);
insert into troy(name, log_type) values('cy', -1);
insert into troy(name, log_type) values('jdy', -1);
create table troy_ivy(id integer primary key, name text, content text, datetime text);
insert into troy_ivy(name, content, datetime) values('troy', 'hello,ivy', '20131117100404');
insert into troy_ivy(name, content, datetime) values('ivy', 'hello,troy', '20131117100504');
create table cy_troy(id integer primary key, name text, content text, datetime text);
insert into cy_troy(name, content, datetime) values('troy', 'hello,cy', '20131117100404');
insert into cy_troy(name, content, datetime) values('cy', 'hello,troy', '20131117100504');
