create table users(id integer primary key, name text, passwd text, fd integer, email text, phone text, tel text);
insert into users(name, passwd, fd, email, phone, tel) values('troy', 'troy', -1, 'troy@smit.com', '13263102327', '6666');
insert into users(name, passwd, fd, email, phone, tel) values('zyy', 'zyy', -1, 'zyy@smit.com', '13263102328', '7777');
create table troy(id integer primary key, name text, log_type integer);
insert into troy(name, log_type) values('zyy', 0);
create table zyy(id integer primary key, name text, log_type integer);
insert into zyy(name, log_type) values('troy', 1);
create table troy_zyy(id integer primary key, name text, content text, datetime text);
create table troy_offline(id integer primary key, name text, content text, datetime text);
create table zyy_offline(id integer primary key, name text, content text, datetime text);
